### ISSUE TITLE
Helm Chart with 2 different versions of the Sensors

### ISSUE THREAD

**Issue by tarrinho** [fortify/helm3-charts#5]
Hello, 

is there a way to have a helm chart with 2 versions of the Sensors? 

The problem is that there are too many people using version 22.1 to change to 22.2 in one day, so the idea is to have at the same time 2 versions of the Sensors. 

Is it possible?

Thanks,
Tarrinho

**Comment by fbordallo** [comment]
Hi,

assuming this issue is related to Scancentral SAST chart, yes, it is posible to add 2 types of sensors using the values file. Check the comments at the `workers:` section (https://github.com/fortify/helm3-charts/blob/e7931adfb658f5516aeead0ff0cd2a989107db0b/charts/scancentral-sast/values.yaml#L135). You need to copy the contents of the worker type you want use (linux or windows) and use the docker image tag for the previous version at the `image:` section. Something like this:

```
 image:
      repository: fortifydocker/scancentral-sast-sensor
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: "22.1"
```

Remember to give a unique key to the worker type (it can't be linux or windows).
